In [12]:

# Determine the number of rows and columns in the dataset.
import pandas
df = pandas.read_csv("Airplane_Crashes_and_Fatalities_Since_1908.csv")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5268
Columns: 13

In [13]:
# Display the last 75 rows of the dataset.
df.tail(75)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
5193,03/15/2008,08:15,"Nbagu, Nigeria",Trade Wings Aviation Ltd.,NaN,Lagos - Bebi Air Strip,Beechcraft 1900D,5N-JAH,UE-322,3.0,3.0,0.0,The plane crashed while en route. Wreckage was...
5194,04/03/2008,11:00,"Lawa, Suriname",Blue Wing Airlines,NaN,Paramaribo - Lawa,Antonov An-28,PZ-TSO,1AJ007-17,19.0,19.0,0.0,While attempting to land the crew aborted the ...
5195,04/09/2008,23:27,"Bundeena, Australia",Avtex Air Services,NaN,Sydney - Brisbane,Swearingen SA227AC Metroliner III,VH-OZA,AC-600,1.0,1.0,0.0,The pilot of the mail plane reported some mino...
5196,04/11/2008,22:15,"Chrisinau, Moldova",Kata Transportation,NaN,"Chrisinau, Moldova - Antalya, Turkey - Sudan",Antonov An-32,ST-AZL,3009,8.0,8.0,0.0,Just minutes after the take off the plane trie...
5197,04/15/2008,14:30,"Goma, Congo",Hewa Bora Airways,NaN,Goma - Kisangani - Kinshasa,McDonnell Douglas DC-9-51,9Q-CHN,47731,85.0,0.0,47.0,"While attempting to takeoff, the plane failed ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,05/20/2009,06:30,"Near Madiun, Indonesia",Military - Indonesian Air Force,NaN,Jakarta - Maduin,Lockheed C-130 Hercules,A-1325,1982,112.0,98.0,2.0,"While on approach, the military transport cras..."
5264,05/26/2009,NaN,"Near Isiro, DemocratiRepubliCongo",Service Air,NaN,Goma - Isiro,Antonov An-26,9Q-CSA,5005,4.0,4.0,NaN,The cargo plane crashed while on approach to I...
5265,06/01/2009,00:15,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,447,Rio de Janeiro - Paris,Airbus A330-203,F-GZCP,660,228.0,228.0,0.0,The Airbus went missing over the AtlantiOcean ...
5266,06/07/2009,08:30,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,NaN,Lourdes de BlanSablon - Port Hope Simpson,Britten-Norman BN-2A-27 Islander,C-FJJR,424,1.0,1.0,0.0,The air ambulance crashed into hills while att...
5267,06/08/2009,NaN,"State of Arunachal Pradesh, India",Military - Indian Air Force,NaN,Mechuka for Jorhat,Antonov An-32,NaN,NaN,13.0,13.0,0.0,The military transport went missing while en r...

In [14]:
# Missing values in the dataset.
df.isnull().sum() # This will show the number of missing values in each column of the dataset.

df.info() # This will show the data types of each column and the number of non-null values in each column.

<class 'pandas.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          5268 non-null   str
 1   Time          3049 non-null   str
 2   Location      5248 non-null   str
 3   Operator      5250 non-null   str
 4   Flight #      1069 non-null   str
 5   Route         3561 non-null   str
 6   Type          5241 non-null   str
 7   Registration  4933 non-null   str
 8   cn/In         4040 non-null   str
 9   Aboard        5246 non-null   float64
 10  Fatalities    5256 non-null   float64
 11  Ground        5246 non-null   float64
 12  Summary       4878 non-null   str
dtypes: float64(3), str(10)
memory usage: 535.2 KB

In [15]:
# Question 5
fatality_locations = df[['Date', 'Location', 'Aboard', 'Fatalities']]
fatality_locations.head()

         Date                            Location  Aboard  Fatalities
0  09/17/1908                 Fort Myer, Virginia     2.0         1.0
1  07/12/1912             AtlantiCity, New Jersey     5.0         5.0
2  08/06/1913  Victoria, British Columbia, Canada     1.0         1.0
3  09/09/1913                  Over the North Sea    20.0        14.0
4  10/17/1913          Near Johannisthal, Germany    30.0        30.0

In [16]:
# Question 6
fatality_locations.loc[fatality_locations['Fatalities'].idxmax(), 'Date']

'03/27/1977'

In [17]:
# Question 7
fatality = fatality_locations.copy()

fatality[['Aboard', 'Fatalities']]
no_fatalities = fatality[fatality['Fatalities'] == 0]
print("Number of crashes with no fatalities:", len(no_fatalities))
no_fatalities

print("Mean passengers aboard:", fatality_locations['Aboard'].mean())
print("Mean fatalities:", fatality_locations['Fatalities'].mean())

Number of crashes with no fatalities: 58
Mean passengers aboard: 27.554517727792604
Mean fatalities: 20.06830289193303

In [18]:
# Question 8
fatality[['Region', 'State/Country']] = fatality['Location'].str.split(',', n=1, expand=True)
fatality.head()

,Date,Location,Aboard,Fatalities,Region,State/Country
0,09/17/1908,"Fort Myer, Virginia",2.0,1.0,Fort Myer,Virginia
1,07/12/1912,"AtlantiCity, New Jersey",5.0,5.0,AtlantiCity,New Jersey
2,08/06/1913,"Victoria, British Columbia, Canada",1.0,1.0,Victoria,"British Columbia, Canada"
3,09/09/1913,Over the North Sea,20.0,14.0,Over the North Sea,NaN
4,10/17/1913,"Near Johannisthal, Germany",30.0,30.0,Near Johannisthal,Germany

In [19]:
top_100 = fatality.sort_values(
    by='Fatalities',
    ascending=False
).head(100)
top_100

,Date,Location,Aboard,Fatalities,Region,State/Country
2963,03/27/1977,"Tenerife, Canary Islands",644.0,583.0,Tenerife,Canary Islands
3568,08/12/1985,"Mt. Osutaka, near Ueno Village, Japan",524.0,520.0,Mt. Osutaka,"near Ueno Village, Japan"
4455,11/12/1996,"Near Charkhidadri, India",349.0,349.0,Near Charkhidadri,India
2726,03/03/1974,"Near Ermenonville, France",346.0,346.0,Near Ermenonville,France
3562,06/23/1985,"AtlantiOcean, 110 miles West of Ireland",329.0,329.0,AtlantiOcean,110 miles West of Ireland
...,...,...,...,...,...,...
4852,04/15/2002,"Busan, South Korea",166.0,128.0,Busan,South Korea
3198,01/21/1980,"Elburz Mtns., near Laskarak, Markazi, Iran",128.0,128.0,Elburz Mtns.,"near Laskarak, Markazi, Iran"
1701,12/16/1960,"Staten Island / Brooklyn, New York",128.0,128.0,Staten Island / Brooklyn,New York
5108,07/09/2006,"Irkutsk, Russia",203.0,128.0,Irkutsk,Russia
1433,06/30/1956,"Grand Canyon, Arizona",128.0,128.0,Grand Canyon,Arizona

In [ ]:
fbc = (
    fatality.groupby('State/Country')['Fatalities']
    .sum()
    .dropna()
    .sort_values(ascending=False)
    .head(25)
)

fbc

import matplotlib.pyplot as plt

fbc.plot.pie(
    autopct='%1.1f%%',
    figsize=(10, 10)
)

plt.ylabel('')
plt.title('Fatalities by Country and or State - Top 25')
plt.show()

KeyError: 'State/Country'